/**
 * Market Analysis Data
 *
 * Auto-generated by scripts/update-listings-nightly.ts
 * Synced nightly from Spark API
 *
 * Includes: active inventory, median price, median DOM, price/sqft, 30-day sold activity
 */

export interface MarketAnalysis {
  activeCount: number;
  medianPrice: number;
  medianDOM: number;
  avgPricePerSqft: number;
  soldCount30d: number;
  soldMedianPrice: number;
  lastUpdated: string;
}

export const marketAnalysisByCity: Record<string, MarketAnalysis> = {
  "ann-arbor-mi": {
    "activeCount": 500,
    "medianPrice": 549000,
    "medianDOM": 0,
    "avgPricePerSqft": null,
    "soldCount30d": 0,
    "soldMedianPrice": 0,
    "lastUpdated": "2026-06-08T18:18:38.882Z"
  },
  "birmingham-mi": {
    "activeCount": 20,
    "medianPrice": 425900,
    "medianDOM": 0,
    "avgPricePerSqft": null,
    "soldCount30d": 0,
    "soldMedianPrice": 0,
    "lastUpdated": "2026-06-08T18:18:38.882Z"
  },
  "bloomfield-hills-mi": {
    "activeCount": 7,
    "medianPrice": 349999,
    "medianDOM": 0,
    "avgPricePerSqft": null,
    "soldCount30d": 0,
    "soldMedianPrice": 0,
    "lastUpdated": "2026-06-08T18:18:38.882Z"
  },
  "bloomfield-township-mi": {
    "activeCount": 8,
    "medianPrice": 478000,
    "medianDOM": 0,
    "avgPricePerSqft": null,
    "soldCount30d": 0,
    "soldMedianPrice": 0,
    "lastUpdated": "2026-06-08T18:18:38.882Z"
  },
  "brighton-mi": {
    "activeCount": 12,
    "medianPrice": 359900,
    "medianDOM": 0,
    "avgPricePerSqft": null,
    "soldCount30d": 0,
    "soldMedianPrice": 0,
    "lastUpdated": "2026-06-08T18:18:38.882Z"
  },
  "clarkston-mi": {
    "activeCount": 2,
    "medianPrice": 564900,
    "medianDOM": 0,
    "avgPricePerSqft": 133,
    "soldCount30d": 0,
    "soldMedianPrice": 0,
    "lastUpdated": "2026-06-08T18:18:38.882Z"
  },
  "clinton-township-mi": {
    "activeCount": 10,
    "medianPrice": 359999,
    "medianDOM": 0,
    "avgPricePerSqft": null,
    "soldCount30d": 0,
    "soldMedianPrice": 0,
    "lastUpdated": "2026-06-08T18:18:38.882Z"
  },
  "detroit-mi": {
    "activeCount": 500,
    "medianPrice": 100000,
    "medianDOM": 0,
    "avgPricePerSqft": null,
    "soldCount30d": 0,
    "soldMedianPrice": 0,
    "lastUpdated": "2026-06-08T18:18:38.883Z"
  },
  "flint-mi": {
    "activeCount": 18,
    "medianPrice": 2000,
    "medianDOM": 0,
    "avgPricePerSqft": null,
    "soldCount30d": 0,
    "soldMedianPrice": 0,
    "lastUpdated": "2026-06-08T18:18:38.883Z"
  },
  "grosse-pointe-mi": {
    "activeCount": 0,
    "medianPrice": 0,
    "medianDOM": 0,
    "avgPricePerSqft": 0,
    "soldCount30d": 0,
    "soldMedianPrice": 0,
    "lastUpdated": "2026-06-08T18:18:38.883Z"
  },
  "grosse-pointe-woods-mi": {
    "activeCount": 2,
    "medianPrice": 619900,
    "medianDOM": 0,
    "avgPricePerSqft": null,
    "soldCount30d": 0,
    "soldMedianPrice": 0,
    "lastUpdated": "2026-06-08T18:18:38.883Z"
  },
  "howell-mi": {
    "activeCount": 8,
    "medianPrice": 520000,
    "medianDOM": 0,
    "avgPricePerSqft": null,
    "soldCount30d": 0,
    "soldMedianPrice": 0,
    "lastUpdated": "2026-06-08T18:18:38.883Z"
  },
  "lake-orion-mi": {
    "activeCount": 0,
    "medianPrice": 0,
    "medianDOM": 0,
    "avgPricePerSqft": 0,
    "soldCount30d": 0,
    "soldMedianPrice": 0,
    "lastUpdated": "2026-06-08T18:18:38.883Z"
  },
  "livonia-mi": {
    "activeCount": 18,
    "medianPrice": 347000,
    "medianDOM": 0,
    "avgPricePerSqft": null,
    "soldCount30d": 0,
    "soldMedianPrice": 0,
    "lastUpdated": "2026-06-08T18:18:38.883Z"
  },
  "macomb-township-mi": {
    "activeCount": 4,
    "medianPrice": 599900,
    "medianDOM": 0,
    "avgPricePerSqft": 185,
    "soldCount30d": 0,
    "soldMedianPrice": 0,
    "lastUpdated": "2026-06-08T18:18:38.883Z"
  },
  "northville-mi": {
    "activeCount": 31,
    "medianPrice": 529900,
    "medianDOM": 0,
    "avgPricePerSqft": null,
    "soldCount30d": 0,
    "soldMedianPrice": 0,
    "lastUpdated": "2026-06-08T18:18:38.883Z"
  },
  "novi-mi": {
    "activeCount": 9,
    "medianPrice": 465000,
    "medianDOM": 0,
    "avgPricePerSqft": null,
    "soldCount30d": 0,
    "soldMedianPrice": 0,
    "lastUpdated": "2026-06-08T18:18:38.883Z"
  },
  "orchard-lake-mi": {
    "activeCount": 5,
    "medianPrice": 459900,
    "medianDOM": 0,
    "avgPricePerSqft": 316,
    "soldCount30d": 0,
    "soldMedianPrice": 0,
    "lastUpdated": "2026-06-08T18:18:38.883Z"
  },
  "oxford-mi": {
    "activeCount": 1,
    "medianPrice": 3499999,
    "medianDOM": 0,
    "avgPricePerSqft": 1458,
    "soldCount30d": 0,
    "soldMedianPrice": 0,
    "lastUpdated": "2026-06-08T18:18:38.883Z"
  },
  "plymouth-mi": {
    "activeCount": 23,
    "medianPrice": 489000,
    "medianDOM": 0,
    "avgPricePerSqft": null,
    "soldCount30d": 0,
    "soldMedianPrice": 0,
    "lastUpdated": "2026-06-08T18:18:38.883Z"
  },
  "rochester-hills-mi": {
    "activeCount": 14,
    "medianPrice": 559900,
    "medianDOM": 0,
    "avgPricePerSqft": null,
    "soldCount30d": 0,
    "soldMedianPrice": 0,
    "lastUpdated": "2026-06-08T18:18:38.883Z"
  },
  "rochester-mi": {
    "activeCount": 9,
    "medianPrice": 339900,
    "medianDOM": 0,
    "avgPricePerSqft": null,
    "soldCount30d": 0,
    "soldMedianPrice": 0,
    "lastUpdated": "2026-06-08T18:18:38.883Z"
  },
  "royal-oak-mi": {
    "activeCount": 7,
    "medianPrice": 415000,
    "medianDOM": 0,
    "avgPricePerSqft": null,
    "soldCount30d": 0,
    "soldMedianPrice": 0,
    "lastUpdated": "2026-06-08T18:18:38.883Z"
  },
  "saline-mi": {
    "activeCount": 73,
    "medianPrice": 460000,
    "medianDOM": 0,
    "avgPricePerSqft": null,
    "soldCount30d": 0,
    "soldMedianPrice": 0,
    "lastUpdated": "2026-06-08T18:18:38.883Z"
  },
  "shelby-township-mi": {
    "activeCount": 12,
    "medianPrice": 399900,
    "medianDOM": 0,
    "avgPricePerSqft": null,
    "soldCount30d": 0,
    "soldMedianPrice": 0,
    "lastUpdated": "2026-06-08T18:18:38.883Z"
  },
  "st-clair-shores-mi": {
    "activeCount": 3,
    "medianPrice": 222000,
    "medianDOM": 0,
    "avgPricePerSqft": 181,
    "soldCount30d": 0,
    "soldMedianPrice": 0,
    "lastUpdated": "2026-06-08T18:18:38.883Z"
  },
  "sterling-heights-mi": {
    "activeCount": 8,
    "medianPrice": 245900,
    "medianDOM": 0,
    "avgPricePerSqft": null,
    "soldCount30d": 0,
    "soldMedianPrice": 0,
    "lastUpdated": "2026-06-08T18:18:38.883Z"
  },
  "troy-mi": {
    "activeCount": 5,
    "medianPrice": 675000,
    "medianDOM": 0,
    "avgPricePerSqft": null,
    "soldCount30d": 0,
    "soldMedianPrice": 0,
    "lastUpdated": "2026-06-08T18:18:38.883Z"
  },
  "warren-mi": {
    "activeCount": 27,
    "medianPrice": 120000,
    "medianDOM": 0,
    "avgPricePerSqft": null,
    "soldCount30d": 0,
    "soldMedianPrice": 0,
    "lastUpdated": "2026-06-08T18:18:38.883Z"
  },
  "west-bloomfield-mi": {
    "activeCount": 10,
    "medianPrice": 349900,
    "medianDOM": 0,
    "avgPricePerSqft": null,
    "soldCount30d": 0,
    "soldMedianPrice": 0,
    "lastUpdated": "2026-06-08T18:18:38.883Z"
  }
};

/**
 * Helper to get market analysis for a specific city
 */
export function getMarketAnalysis(citySlug: string): MarketAnalysis | undefined {
  return marketAnalysisByCity[citySlug];
}

/**
 * Helper to get all market analysis data
 */
export function getAllMarketAnalysis(): Record<string, MarketAnalysis> {
  return marketAnalysisByCity;
}
