/**
 * Market Analysis Data
 *
 * Auto-generated by scripts/update-listings-nightly.ts
 * Synced nightly from Spark API
 *
 * Includes: active inventory, median price, median DOM, price/sqft, 30-day sold activity
 */

export interface MarketAnalysis {
  activeCount: number;
  medianPrice: number;
  medianDOM: number;
  avgPricePerSqft: number | null;
  soldCount30d: number;
  soldMedianPrice: number;
  lastUpdated: string;
}

export const marketAnalysisByCity: Record<string, MarketAnalysis> = {
  "ann-arbor-mi": {
    "activeCount": 500,
    "medianPrice": 545000,
    "medianDOM": 0,
    "avgPricePerSqft": null,
    "soldCount30d": 0,
    "soldMedianPrice": 0,
    "lastUpdated": "2026-06-08T18:55:10.930Z"
  },
  "birmingham-mi": {
    "activeCount": 500,
    "medianPrice": 669900,
    "medianDOM": 0,
    "avgPricePerSqft": null,
    "soldCount30d": 0,
    "soldMedianPrice": 0,
    "lastUpdated": "2026-06-08T18:55:10.931Z"
  },
  "bloomfield-hills-mi": {
    "activeCount": 500,
    "medianPrice": 899999,
    "medianDOM": 0,
    "avgPricePerSqft": null,
    "soldCount30d": 0,
    "soldMedianPrice": 0,
    "lastUpdated": "2026-06-08T18:55:10.931Z"
  },
  "bloomfield-township-mi": {
    "activeCount": 500,
    "medianPrice": 899999,
    "medianDOM": 0,
    "avgPricePerSqft": null,
    "soldCount30d": 0,
    "soldMedianPrice": 0,
    "lastUpdated": "2026-06-08T18:55:10.931Z"
  },
  "brighton-mi": {
    "activeCount": 94,
    "medianPrice": 339900,
    "medianDOM": 0,
    "avgPricePerSqft": null,
    "soldCount30d": 0,
    "soldMedianPrice": 0,
    "lastUpdated": "2026-06-08T18:55:10.931Z"
  },
  "clarkston-mi": {
    "activeCount": 2,
    "medianPrice": 564900,
    "medianDOM": 0,
    "avgPricePerSqft": 133,
    "soldCount30d": 0,
    "soldMedianPrice": 0,
    "lastUpdated": "2026-06-08T18:55:10.931Z"
  },
  "clinton-township-mi": {
    "activeCount": 500,
    "medianPrice": 269900,
    "medianDOM": 0,
    "avgPricePerSqft": null,
    "soldCount30d": 0,
    "soldMedianPrice": 0,
    "lastUpdated": "2026-06-08T18:55:10.931Z"
  },
  "detroit-mi": {
    "activeCount": 500,
    "medianPrice": 115000,
    "medianDOM": 0,
    "avgPricePerSqft": null,
    "soldCount30d": 0,
    "soldMedianPrice": 0,
    "lastUpdated": "2026-06-08T18:55:10.931Z"
  },
  "flint-mi": {
    "activeCount": 500,
    "medianPrice": 65000,
    "medianDOM": 0,
    "avgPricePerSqft": null,
    "soldCount30d": 0,
    "soldMedianPrice": 0,
    "lastUpdated": "2026-06-08T18:55:10.931Z"
  },
  "grosse-pointe-mi": {
    "activeCount": 54,
    "medianPrice": 320000,
    "medianDOM": 0,
    "avgPricePerSqft": null,
    "soldCount30d": 0,
    "soldMedianPrice": 0,
    "lastUpdated": "2026-06-08T18:55:10.931Z"
  },
  "grosse-pointe-woods-mi": {
    "activeCount": 74,
    "medianPrice": 324900,
    "medianDOM": 0,
    "avgPricePerSqft": null,
    "soldCount30d": 0,
    "soldMedianPrice": 0,
    "lastUpdated": "2026-06-08T18:55:10.931Z"
  },
  "howell-mi": {
    "activeCount": 500,
    "medianPrice": 428155,
    "medianDOM": 0,
    "avgPricePerSqft": null,
    "soldCount30d": 0,
    "soldMedianPrice": 0,
    "lastUpdated": "2026-06-08T18:55:10.931Z"
  },
  "lake-orion-mi": {
    "activeCount": 0,
    "medianPrice": 0,
    "medianDOM": 0,
    "avgPricePerSqft": 0,
    "soldCount30d": 0,
    "soldMedianPrice": 0,
    "lastUpdated": "2026-06-08T18:55:10.931Z"
  },
  "livonia-mi": {
    "activeCount": 500,
    "medianPrice": 284900,
    "medianDOM": 0,
    "avgPricePerSqft": null,
    "soldCount30d": 0,
    "soldMedianPrice": 0,
    "lastUpdated": "2026-06-08T18:55:10.931Z"
  },
  "macomb-township-mi": {
    "activeCount": 500,
    "medianPrice": 479999,
    "medianDOM": 0,
    "avgPricePerSqft": null,
    "soldCount30d": 0,
    "soldMedianPrice": 0,
    "lastUpdated": "2026-06-08T18:55:10.931Z"
  },
  "northville-mi": {
    "activeCount": 500,
    "medianPrice": 599000,
    "medianDOM": 0,
    "avgPricePerSqft": null,
    "soldCount30d": 0,
    "soldMedianPrice": 0,
    "lastUpdated": "2026-06-08T18:55:10.931Z"
  },
  "novi-mi": {
    "activeCount": 37,
    "medianPrice": 330000,
    "medianDOM": 0,
    "avgPricePerSqft": null,
    "soldCount30d": 0,
    "soldMedianPrice": 0,
    "lastUpdated": "2026-06-08T18:55:10.931Z"
  },
  "orchard-lake-mi": {
    "activeCount": 85,
    "medianPrice": 459900,
    "medianDOM": 0,
    "avgPricePerSqft": null,
    "soldCount30d": 0,
    "soldMedianPrice": 0,
    "lastUpdated": "2026-06-08T18:55:10.931Z"
  },
  "oxford-mi": {
    "activeCount": 80,
    "medianPrice": 499000,
    "medianDOM": 0,
    "avgPricePerSqft": null,
    "soldCount30d": 0,
    "soldMedianPrice": 0,
    "lastUpdated": "2026-06-08T18:55:10.931Z"
  },
  "plymouth-mi": {
    "activeCount": 500,
    "medianPrice": 489000,
    "medianDOM": 0,
    "avgPricePerSqft": null,
    "soldCount30d": 0,
    "soldMedianPrice": 0,
    "lastUpdated": "2026-06-08T18:55:10.932Z"
  },
  "rochester-hills-mi": {
    "activeCount": 500,
    "medianPrice": 499900,
    "medianDOM": 0,
    "avgPricePerSqft": null,
    "soldCount30d": 0,
    "soldMedianPrice": 0,
    "lastUpdated": "2026-06-08T18:55:10.932Z"
  },
  "rochester-mi": {
    "activeCount": 500,
    "medianPrice": 437500,
    "medianDOM": 0,
    "avgPricePerSqft": null,
    "soldCount30d": 0,
    "soldMedianPrice": 0,
    "lastUpdated": "2026-06-08T18:55:10.932Z"
  },
  "royal-oak-mi": {
    "activeCount": 500,
    "medianPrice": 347000,
    "medianDOM": 0,
    "avgPricePerSqft": null,
    "soldCount30d": 0,
    "soldMedianPrice": 0,
    "lastUpdated": "2026-06-08T18:55:10.932Z"
  },
  "saline-mi": {
    "activeCount": 500,
    "medianPrice": 544999,
    "medianDOM": 0,
    "avgPricePerSqft": null,
    "soldCount30d": 0,
    "soldMedianPrice": 0,
    "lastUpdated": "2026-06-08T18:55:10.932Z"
  },
  "shelby-township-mi": {
    "activeCount": 500,
    "medianPrice": 439999,
    "medianDOM": 0,
    "avgPricePerSqft": null,
    "soldCount30d": 0,
    "soldMedianPrice": 0,
    "lastUpdated": "2026-06-08T18:55:10.932Z"
  },
  "st-clair-shores-mi": {
    "activeCount": 79,
    "medianPrice": 229900,
    "medianDOM": 0,
    "avgPricePerSqft": null,
    "soldCount30d": 0,
    "soldMedianPrice": 0,
    "lastUpdated": "2026-06-08T18:55:10.932Z"
  },
  "sterling-heights-mi": {
    "activeCount": 500,
    "medianPrice": 319000,
    "medianDOM": 0,
    "avgPricePerSqft": null,
    "soldCount30d": 0,
    "soldMedianPrice": 0,
    "lastUpdated": "2026-06-08T18:55:10.932Z"
  },
  "troy-mi": {
    "activeCount": 500,
    "medianPrice": 309900,
    "medianDOM": 0,
    "avgPricePerSqft": null,
    "soldCount30d": 0,
    "soldMedianPrice": 0,
    "lastUpdated": "2026-06-08T18:55:10.932Z"
  },
  "warren-mi": {
    "activeCount": 500,
    "medianPrice": 145000,
    "medianDOM": 0,
    "avgPricePerSqft": null,
    "soldCount30d": 0,
    "soldMedianPrice": 0,
    "lastUpdated": "2026-06-08T18:55:10.932Z"
  },
  "west-bloomfield-mi": {
    "activeCount": 90,
    "medianPrice": 449900,
    "medianDOM": 0,
    "avgPricePerSqft": null,
    "soldCount30d": 0,
    "soldMedianPrice": 0,
    "lastUpdated": "2026-06-08T18:55:10.932Z"
  }
};

/**
 * Helper to get market analysis for a specific city
 */
export function getMarketAnalysis(citySlug: string): MarketAnalysis | undefined {
  return marketAnalysisByCity[citySlug];
}

/**
 * Helper to get all market analysis data
 */
export function getAllMarketAnalysis(): Record<string, MarketAnalysis> {
  return marketAnalysisByCity;
}
